default: PhysBAM

PhysBAM:
	$(MAKE) -f ${CURDIR}/Makefile.PhysBAM

#PhysBAM_OpenGL:
#	$(MAKE) -f Makefile.PhysBAM_OpenGL

%:
	$(MAKE) -f ${CURDIR}/Makefile.PhysBAM $@
#	$(MAKE) -f Makefile.PhysBAM_OpenGL $@
